### ISSUE TITLE
API Bug: subscribe orderbook failed with `options` instrument name

### ISSUE THREAD

**Issue by tayadelmar** [adampointer/go-deribit#16]
Example from API Console:
API Request:
```json
{
    "jsonrpc": "2.0",
    "id": 3997,
    "method": "public/subscribe",
    "params": {
        "channels": [
            "book.BTC-21JUN19-10000-C.none.1.100ms"
        ]
    }
}
```
API Results and notifications:
```json
{
    "jsonrpc": "2.0",
    "id": 3997,
    "result": [],
    "usIn": 1561053224590810,
    "usOut": 1561053224590859,
    "usDiff": 49,
    "testnet": true
} 
```
If subscription was subscribed successfully the `result` tag should contain a confirmation. 

NOTE: `"result": []` is a fishy way to notify users about unsuccessful subscribe to a channel.

**Comment by tayadelmar** [comment]
Example of successful orderbook subscribe with a `futures` instrument name:
API Request:
```json
{
    "jsonrpc": "2.0",
    "id": 9613,
    "method": "public/subscribe",
    "params": {
        "channels": [
            "book.ETH-PERPETUAL.none.1.100ms"
        ]
    }
}
```
API Results and notifications:
```json
{
    "jsonrpc": "2.0",
    "id": 8483,
    "result": [
        "book.ETH-PERPETUAL.none.1.100ms"
    ],
    "usIn": 1561056692810072,
    "usOut": 1561056692810124,
    "usDiff": 52,
    "testnet": true
}
```

**Comment by adampointer** [comment]
The behaviour is the same in the API console as via the library. Maybe liquidity is too low on the options to see notifications come through. I agree, confirmation that a sub has been successful is severely lacking in their API. I think I will close this as a Deribit issue.
