### ISSUE TITLE
GetPrivateGetSettlementHistoryByCurrency/Instrument

### ISSUE THREAD

**Issue by BlndMrn** [adampointer/go-deribit#3]
When trying to get settlement history:

> client := e.Client()
	// Account settlement history
	history, err := client.GetPrivateGetSettlementHistoryByCurrency(&operations.GetPrivateGetSettlementHistoryByCurrencyParams{Currency: "BTC"})
	if err != nil {
		log.Fatalf("Error getting account settlement: %s", err)
	}

retrieves err: 
`Error getting account settlement: json: cannot unmarshal object into Go struct field PrivateSettlementResponse.result of type []string`
Tried to change swaqqer struct. And as a result answer was nil. How to solve the problem?

**Comment by adampointer** [comment]
Hi

It seems that the swagger is incorrect. I am not surprised tbh as I had to do a lot of cleaning up. I will take a look at fixing it.

**Comment by adampointer** [comment]
@BlindMoron give that a try. There was an extraneous `type:"array"` in the swagger def for the response.
