### ISSUE TITLE
Add cancel label

### ISSUE THREAD

**Issue by kprimice** [adampointer/go-deribit#31]
Anyone can help with merging this #30?

**Comment by adampointer** [comment]
As mentioned in the PR this is merged but I will generate the code for you in the coming days.

**Comment by kprimice** [comment]
Thanks @adampointer I appreciate it. Let me know when it's done :)

**Comment by adampointer** [comment]
Done in v3.2.0

There was a bit of a refactor. I believe this is because there is a newer version of go-swagger now. It has reorganised packages around. Look in the acceptance test file if you need a clue.
