### ISSUE TITLE
GetPrivateCancelAll() and GetPrivateCancel() disappeared?

### ISSUE THREAD

**Issue by kprimice** [adampointer/go-deribit#32]
I think last swagger update removed GetPrivateCancelAll() and GetPrivateCancel() methods.

```
type *private.Client has no field or method GetPrivateCancel
type *private.Client has no field or method GetPrivateCancelAll
```

**Comment by adampointer** [comment]
They have moved from the private namespace to trading.

See `v3/client/trading/trading_client.go`

**Comment by kprimice** [comment]
Thanks!
