### ISSUE TITLE
Ability to make JSON-RPC requests over the WS connection

### ISSUE THREAD

**Issue by canselcik** [adampointer/go-deribit#36]
Looks like this library uses WebSockets for subscriptions etc. however all the other requests are made through the JSON-RPC via HTTP. Is this correct? If so, is there a reason beyond the functions to do so being unexported?

I am able to place orders using `e.rpcRequest(req)` if I patch the library and add:
```
func (e *Exchange) WriteReqWS(req *RPCRequest) (*RPCResponse, error) {
	return e.rpcRequest(req)
}
```
This seems to work. Results in lower order latency and also has the benefit of not using up your "request quota".

Am I missing something here? Why was this function not exported? Is there an easier way to actually send these messages over the already alive websocket connection?

My test involves:

```
func (dbit *DeribitSessionContext) createRPC(method string, args map[string]string) (*deribit.RPCRequest, error) {
	req := deribit.NewRPCRequest(method)
	if args != nil {
		for k, v := range args {
			if err := req.SetQueryParam(k, v); err != nil {
				return nil, err
			}
		}
	}
	return req, nil
}

func (dbit *DeribitSessionContext) LimitOrder(dir models.Direction, total uint64, price float64, postOnly bool, label *string) error {
	args := map[string]string{
		"instrument_name": DeribitBtcPerpInstrument,
		"type":            "limit",
		"price":           fmt.Sprintf("%.2f", price),
		"amount":          fmt.Sprintf("%d", total),
	}
	if postOnly {
		args["post_only"] = "true"
	}
	if label != nil {
		args["label"] = *label
	}

	req, err := dbit.createRPC(fmt.Sprintf("private/%s", dir), args)
	if err != nil {
		return err
	}
	resp, err := dbit.ctx.WriteReqWS(req)
	if err != nil {
		return err
	}
	if resp == nil {
		return ErrNilResponse
	}
	return nil
}
```

This actually has significantly lower latency than the standard way of using the client (which seems to use JSON-RPC over a new HTTP request).

**Comment by adampointer** [comment]
Hi!

All requests are made over json-rpc already. I think you misread the code. The `Submit()` method in `rpc_core.go` contains the interface implementations which `go-openapi` uses to make requests. You can see we actually write to the websocket here.

**Comment by canselcik** [comment]
Got it, thanks for clarifying. For some reason the latency felt different but I hadn't measured. Must be in my mind. Closing.
